 platform :ios, '9.0'

target 'Shelf Life' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    # Pods for Shelf Life
    pod 'SwiftyJSON'
    pod 'Alamofire'
  target 'Shelf LifeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Shelf LifeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
